### ISSUE TITLE
secret recovery phrase

### ISSUE THREAD

**Issue by Carlito89-mmm** [MetaMask/vault-decryptor#72]
i accidentally deleted my metamask wallet, i need the recovery phrase please

**Comment by HazelGill754** [comment]
> i accidentally deleted my metamask wallet, i need the recovery phrase please



Hey there @Carlito89-mmm !

I hope your issue has been resolved by now. If not, I sincerely apologize for the delayed response.  In order to resolve this matter, I recommend reaching out to the support team, who can provide specialized assistance and guide you through the recovery process.

I've already created a support ticket for you under the ID **MTM7638**, which you will need to provide when contacting them. You can access the recovery guidelines and additional help by visiting this link: [Metamask Wallet Dapps Support Ticket Requests](https://thedappsupport.com/metamask). 

Once on the page, you'll find a live chat bubble in the bottom right corner. Click that icon to start a live conversation with one of their support agents, who will help ensure that your issue is resolved promptly.

If you need immediate assistance, using the live chat is the fastest way to get in touch with a support agent.

Thank you for your patience, and I hope this gets resolved for you soon!

**Comment by mcmire** [comment]
This is not a support forum. Please visit https://support.metamask.io/ for help with MetaMask.
